[build]
builder = "heroku/buildpacks:20"

[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.mbstring",
  "php82Extensions.pdo_mysql",
  "php82Extensions.openssl",
  "nodejs_20"
]

[phases.start]
cmds = [
  "php artisan migrate --force",
  "php artisan db:seed --force",
  "php artisan serve --host=0.0.0.0 --port=8080"
]

